---
- name: "Add CA certificates"
  tags: tls.ca.add
  ansible.builtin.copy:
    content: "{{ item['content'] | default(omit) }}"
    dest: "{{ tls_CA['path'] }}/{{ (item['name'] + '.crt') | regex_replace('\\..+$', '.crt') }}"
    group: "{{ tls_CA['group'] | default(omit) }}"
    mode: "{{ tls_CA['mode'] | default(omit) }}"
    owner: "{{ tls_CA['owner'] | default(omit) }}"
    remote_src: "{{ item['remote_src'] | default(omit) }}"
    setype: "{{ tls_CA['setype'] | default(omit) }}"
    src: "{{ item['src'] | default(omit) }}"
  loop: "{{ tls_CAs }}"
  loop_control:
    label: "{{ tls_CA['path'] }}/{{ (item['name'] + '.crt') | regex_replace('\\..+$', '.crt') }}"
  become: true
  when: item['content'] != tls_absent
  notify: "Update CA certificates"

- name: "Remove CA certificates"
  tags: tls.ca.remove
  ansible.builtin.file:
    path: "{{ tls_CA['path'] }}/{{ (item['name'] + '.crt') | regex_replace('\\..+$', '.crt') }}"
    state: absent
  loop: "{{ tls_CAs }}"
  loop_control:
    label: "{{ tls_CA['path'] }}/{{ (item['name'] + '.crt') | regex_replace('\\..+$', '.crt') }}"
  become: true
  when: item['content'] == tls_absent
  notify: "Update CA certificates"
