---
- name: "Manage CA certificates"
  tags:
    - tls
    - tls.ca
  ansible.builtin.import_tasks: "CA/{{ ansible_system }}.yaml"

- name: "Manage TLS keys and certificates"
  tags:
    - tls
    - tls.key
    - tls.crt
  ansible.builtin.import_tasks: "crt/{{ ansible_system }}.yaml"

- name: "Manage TLS certificates in Windows store"
  tags:
    - tls
    - tls.store
  ansible.builtin.import_tasks: "store.yaml"
  when: ansible_os_family == "Windows"
