---
- name: "Create parent directory on Linux"
  tags: tls.crt.add
  ansible.builtin.file:
    dest: "{{ item['path'] | mandatory | dirname }}"
    group: "{{ item['group'] | default(omit) }}"
    mode: "{{ item['mode'] | default(omit) }}"
    owner: "{{ item['owner'] | default(omit) }}"
    state: directory
  loop: "{{ tls_keys | union(tls_crts) }}"
  loop_control:
    label: "{{ item['path'] | dirname }}"
  when:
    - (item['content'] | default('')) != tls_absent
    - item['path'] is contains('/')

- name: "Create TLS certificate file on Linux"
  tags: tls.crt.add
  ansible.builtin.copy:
    content: "{{ item['content'] | default(omit) }}"
    dest: "{{ item['path'] | mandatory }}"
    group: "{{ item['group'] | default(omit) }}"
    mode: "{{ item['mode'] | default(omit) }}"
    owner: "{{ item['owner'] | default(omit) }}"
    remote_src: "{{ item['remote_src'] | default(omit) }}"
    setype: "{{ item['setype'] | default(omit) }}"
    src: "{{ item['src'] | default(omit) }}"
  loop: "{{ tls_keys | union(tls_crts) }}"
  loop_control:
    label: "{{ item['path'] }}"
  when:
    - (item['content'] | default('')) != tls_absent

- name: "Remove keys and certificates on Linux"
  tags: tls.crt.remove
  ansible.builtin.file:
    path: "{{ item['path'] | mandatory }}"
    state: absent
  loop: "{{ tls_keys | union(tls_crts) }}"
  loop_control:
    label: "{{ item['path'] | mandatory }}"
  when:
    - (item['content'] | default('')) == tls_absent
