---
- name: "Update CA certificates in Debian"
  ansible.builtin.command: /usr/sbin/update-ca-certificates
  when: ansible_os_family == "Debian"
  changed_when: true
  become: true
  listen: "Update CA certificates"

- name: "Update CA certificates in RedHat"
  ansible.builtin.command: /bin/update-ca-trust
  when: ansible_os_family == "RedHat"
  changed_when: true
  become: true
  listen: "Update CA certificates"
